### ISSUE TITLE
Using Razor Generator Compile Aseembly

### ISSUE THREAD

**Issue by vyelchuri** [RickStrahl/Westwind.RazorHosting#10]
If i want to generate my razor template during compile time instead of run time i am using **[RazorGenerator](https://github.com/RazorGenerator/RazorGenerator)**

How to use compile id in place of compiled assembly exists.

**Comment by RickStrahl** [comment]
Not sure what you're asking.

**Comment by vyelchuri** [comment]
While using the "RazorFolderHostContainer" we are loading razor templates as file structure. There is any feature i can load the razor templates pre-compiled assembly instead. @RickStrahl 


![image](https://user-images.githubusercontent.com/18292331/28092488-8ae9db40-6661-11e7-9cd1-55b9a20f2f3a.png)

**Comment by RickStrahl** [comment]
I'm not sure how you would be able to do that. Doesn't that kind of miss the whole point of using a template engine in the first place, especially in a non-Web app?

You'd start with new HostContainer implementation that can store and restore pre-compiled assemblies and load the types from there. HostContainers just need a reference to the resulting assembly which would be assumed to be pre-compiled. I don't even think you need to use RazorGenerator for that - if you have some storage mechanism you can just run the app and store the compiled templates either on disk or some other storage and then load the assembly from there.

Doable but beyond to scope of what I will implement.

Frankly I think this falls into the pre-mature optimization area since assemblies cache after first load anyway and initial load overhead is you see is mostly the Razor Runtime itself firing up, not compilation of code.
