### ISSUE TITLE
Is this library ASP.NET Core ready?

### ISSUE THREAD

**Issue by drauch** [RickStrahl/Westwind.RazorHosting#14]
Is it using ASP.NET Core or the full-blown, old, System.Web.Mvc ?

**Comment by RickStrahl** [comment]
This is based on Razor 3 for full framework and  no it doesn't run ASP.NET Core. It doesn't use MVC - it uses the raw Razor runtimes, so no System.Web dependency.

I don't see any reason to port to .NET Core since .NET Core only support server apps that can directly use the Razor features in ASP.NET Core natively.

**Comment by ahmad-moussawi** [comment]
console apps/microservices can also benefit from a template engine like this one, so I think you should reconsider your decision about porting it to netcore

**Comment by RickStrahl** [comment]
Why would you not use Razor in microservices through the ASP.NET pipeline? Adding an external engine is not going to be any more lightweight than what ASP.ENT Core provides natively.

**Comment by tanveerbadar** [comment]
My microservice is an Azure function app with no associated ASP.NET runtime (as far as I can tell), and a queue trigger. Of course it might be mistaken and not know enough yet to get access to ASP.NET even there.
