### ISSUE TITLE
Generated source files should use fully qualified names for Westwind classes to avoid compile errors

### ISSUE THREAD

**Issue by ManfredLange** [RickStrahl/Westwind.RazorHosting#24]
When Westwind.RazorHost creates a C# file, it includes a statement `using Westwind.RazorHosting;`

This leads to compile errors as class names within that namespace may exist in a different namespace.

For example: class `HtmlHelper` exists both as in namespace `System.Web.Mvc` but also in `Westwind.RazorHost`.

Possible solution: the generated C# code should not use `using Westwind.RazorHosting;` but instead always use fully qualified names for all of its own classes used in any of the generated sources file.

**Comment by RickStrahl** [comment]
MVC? How are you getting the MVC features inside of your templates? HtmlHelper is an MVC thing which isn't part of the hosted Razor runtime and as far as I know you can't easily use the MVC components inside of the templates because all the types are duplicating the behavior of the MVC features.

So I'm not sure how this applies...

I'm not sure what would break by removing the namespace - Most objects you need are referenced through template properties so it might not be that important that it's there.

**Comment by ManfredLange** [comment]
We use quite a few partials in our system. Some of them are directly rendered in views. Others are sent back rendered to a string in a json response to an ajax request by a javascript. Within those partials we may for example render links using `@Html.ActionLink(..)` etc. Or we may use `@Url.Content(...)`. Property `@Html` returns an instance of `HtmlHelper` while `@Url` returns an instance of `UrlHelper`. These two classes as well as class `HtmlUtility` are in namespace `System.Web.Mvc`

I see two issues here:
1. `HtmlHelper` is a type name that is also used in namespace `Westwind.RazorHosting` leading to ambiguities. To avoid this issue, it would be good if all rendered code was using fully qualified names for all types. While we normally wouldn't always use fully qualified names in source code written by humans, I think it's not a problem in generated code.
2. `Url` and `Html` are members in class `System.Web.Mvc.WebViewPage<TModel>`. This may require a bit more to make this work. Class `Westwind.RazorHosting.RazorTemplateBase` has a property `Html` that returns `HtmlHelper`. However, that is `Westwind.RazorHosting.HtmlHelper` which is limited in it's functionality, e.g. it does not have method `ActionLink(...)`. Because `RazorTemplateBase.Html` is of type `Westwind.RazorHost.Html` it's not possible to assign it an instance of `System.Web.Mvc.HtmlHelper` (or `System.Web.Mvc.HtmlHelper<TModel> strictly speaking).

It is entirely possible that `Westwind.RazorHosting` was never meant to support this scenario. On the other hand, just because `Westwind.RazorHosting` doesn't have any ASP.NET or MVC dependencies, it shouldn't rule out it's use within an ASP.NET or MVC context. I am not sure, though, how this could be achieved. Perhaps with a host container class and template base class that we need to implement?

What are your thoughts?

**Comment by ManfredLange** [comment]
I should add that we have two scenarios that we want to support:
1. Production: The code runs within a regular ASP.NET MVC application. HttpContext is available.
2. Testing: We test controllers in isolation. HttpContext does not exist. Creating a mock is - as we know - quite a challenge.

Those two in combination lead us down the path of using solution(s) that allow rendering an HTML string given a razor-based template plus a model. If we can make this work reliably we already have other use cases in our systems, e.g. emailing.

**Comment by RickStrahl** [comment]
You may be missing the point here. There is no System.Web.Mvc in this implementation. If you're adding it those helpers won't actually work because they have dependencies on running inside of a System.Web application that has an HttpContext that's not available in an offline scenario for which this solution is meant. 

If you're running this inside of an MVC Web application there are better ways to achieve what you want than using this library - and you can use the full MVC Razor engine which has many more features than what's provided in this library.

Specifcally:
https://weblog.west-wind.com/posts/2012/May/30/Rendering-ASPNET-MVC-Views-to-String

So no this isn't a supported scenario. This library does work in the context of a Web environment but it'll still have to use its own internal objects and not the MVC ones because those are not binary compatible.

**Comment by ManfredLange** [comment]
Yes, I see your point. For testing that is a problem, though, since when you instantiate a controller to test it, then there is no HttpContext.

How would you test a controller object in isolation?

**Comment by RickStrahl** [comment]
Not sure that's not something I do typically - I usually test down the business layer, but not to the controller level and certainly not to the HTML level.

But there are ways to do this I guess:
https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/unit-testing/creating-unit-tests-for-asp-net-mvc-applications-cs

This is much easier in ASP.NET Core as you can instantiate the pipeline entirely in memory and trigger requests all the way through the view result.

**Comment by ManfredLange** [comment]
Thank you for your assistance, Rick, and for sharing this code with the developer community.

**Comment by ManfredLange** [comment]
Would you consider pull requests for this repository/project?
