### ISSUE TITLE
reference needed for Html helpers?

### ISSUE THREAD

**Issue by cscoon** [RickStrahl/Westwind.RazorHosting#27]
I am using a static RazorFolderHostContainer host and passing my model into a template from disk.  When I call RenderTemplate I get these errors:

- 'Westwind.RazorHosting.HtmlHelper' does not contain a definition for 'DisplayFor' and no extension method 'DisplayFor' accepting a first argument of type 'Westwind.RazorHosting.HtmlHelper' could be found (are you missing a using directive or an assembly reference?)

I was under the impression that DisplayFor would work according to this from the Readme.md: 

> Partials, Helpers and Layout pages are supported only in the RazorFolderHost implementation of this library.

I installed the MVC NuGet and added this line to bring in the class that holds the DisplayFor method, but the error persists:

`host.AddAssemblyFromType(typeof(System.Web.Mvc.Html.DisplayExtensions));`

**Comment by RickStrahl** [comment]
HtmlHelper is only partially implemented. DisplayFor etc. doesn't work because it makes not sense as there is no real databinding in a local instance of Razor (ie. you're not posting the data anywhere and you can always access the model directly).

Remember this library **is not ASP.NET MVC** - it's a bare template engine that provides some of the features of MVC Razor that make sense for a local implementation. It's not a full implementation of MVC's Razor features and will never have that as that doesn't make sense outside the context of a Web application.
